Algoritmo "medidas"

Var
A, B, C, areaquad, areatri, areatra: real

Inicio
escreva ("Digite a medida A: ")
leia (A)
escreva ("Digite a medida B: ")
leia (B)
escreva ("Digite a medida C: ")
leia (C)
areaquad <- exp (A, 2)
areatri <- A * B / 2
areatra <- (A + B)* C / 2
escreval ("AREA DO QUADRADO= ", areaquad:8:3)
escreval ("AREA DO TRIANGULO= ", areatri:8:3)
escreval ("AREA DO TRAPEZIO= ", areatra:8:3)

Fimalgoritmo