Algoritmo "idades"

Var
 nome1, nome2 : caractere
 idade1, idade2, media : real

Inicio
  escreval ("Nome da primeira pessoa: ")
  leia (nome1)
  escreval ("Idade da primeira pessoa: ")
  leia (idade1)
  escreval ("Nome da segunda pessoa: ")
  leia (nome2)
  escreval ("Idade da segunda pessoa: ")
  leia (idade2)
  
  media <- (idade1 + idade2)/2
  
  escreva ("A idade media de ", nome1, " e ", nome2, " eh ", media)

Fimalgoritmo